version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '5173:80'
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: plagiarism-checker-network
